# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accession',
            fields=[
                ('number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('created', models.DateField(db_index=True)),
                ('acquisition_method', models.CharField(db_index=True, max_length=50)),
                ('format', models.CharField(db_index=True, max_length=50)),
                ('location', models.CharField(db_index=True, max_length=50)),
                ('volumes', models.IntegerField()),
                ('titles', models.IntegerField()),
                ('serial_added_volume', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CatEdit',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('edit_date', models.DateField(db_index=True)),
                ('bib', models.CharField(max_length=15)),
                ('mat_type', models.CharField(db_index=True, max_length=15)),
                ('editor', models.CharField(db_index=True, max_length=50)),
                ('type', models.CharField(db_index=True, max_length=50)),
                ('source', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryAccession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('volumes', models.IntegerField()),
                ('titles', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=50)),
                ('acquisition_method', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryCatEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_date', models.DateField()),
                ('mat_type', models.CharField(max_length=15)),
                ('editor', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('source', models.CharField(blank=True, max_length=15, null=True)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
